name: Gitpages

on:
  push:
    branches:
      - "main"
jobs: 
    build:
      runs-on: windows-latest

      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Install and build
          run:  npm install && npm run docs:build

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.3.0
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: docs/.vuepress/dist 
          